development:
  vkontakte_app_id: <%= ENV["VK_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_SECRET"] %>

  github_app_id: <%= ENV["GITHUB_ID"] %>
  github_app_secret: <%= ENV["GITHUB_SECRET"] %>

production:
  vkontakte_app_id: <%= ENV["VK_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_SECRET"] %>

  github_app_id: <%= ENV["GITHUB_ID"] %>
  github_app_secret: <%= ENV["GITHUB_SECRET"] %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
