development:
  vkontakte_app_id: 6605257
  vkontakte_app_secret: OXvYktPjrWf0chrLjmSN

  github_app_id: 1c20536ec1fc2fc563f8
  github_app_secret: 543037a97ed8b669f9138c73e072e5ae3087bc46


  twitter_app_id: DMPqPUT6evCIwc2Czxrv3dvL7
  twitter_app_secret: uA40RqlwaM8KJnz05IOnatlxYPX4onF4zEcL3FQJWbm1qIkBAg
