development:
  vkontakte_app_id: 6605257
  vkontakte_app_secret: OXvYktPjrWf0chrLjmSN

  github_app_id: 1c20536ec1fc2fc563f8
  github_app_secret: 543037a97ed8b669f9138c73e072e5ae3087bc46

production:
  vkontakte_app_id: <%= ENV["VK_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_SECRET"] %>

  github_app_id: <%= ENV["GITHUB_ID"] %>
  github_app_secret: <%= ENV["GITHUB_SECRET"] %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
